"use client";
import { create } from "zustand";
import type { Account, AppData, Transaction, TransactionType, Workspace } from "@/domain/models";
import { LocalAppRepository } from "@/repositories/local/app.repository";
import { emptyData } from "@/services/empty-data";
import { seedData } from "@/services/seed";
import { isFinancialDate } from "@/services/financial-date";
import { isPositiveMoney, roundMoney } from "@/services/money";
const repo=new LocalAppRepository();
export type TransactionInput={type:TransactionType;amount:number;category:string;accountId:string;destinationAccountId?:string;date:string;description:string;notes?:string;recurring?:boolean};
type State={data:AppData;hydrated:boolean;workspace:Workspace;drawerOpen:boolean;editingTransactionId:string|null;draftTransactionType:TransactionType;busy:boolean;error:string|null;hydrate:()=>Promise<void>;setWorkspace:(w:Workspace)=>void;setPeriod:(p:string)=>Promise<void>;openDrawer:(id?:unknown)=>void;closeDrawer:()=>void;addTransaction:(v:TransactionInput)=>Promise<void>;updateTransaction:(id:string,v:TransactionInput)=>Promise<void>;deleteTransaction:(id:string)=>Promise<void>;createAccount:(v:Pick<Account,"name"|"type"|"initialBalance"|"currency">)=>Promise<void>;updateAccount:(id:string,v:Partial<Pick<Account,"name"|"type"|"initialBalance">>)=>Promise<void>;archiveAccount:(id:string)=>Promise<void>;updateData:(fn:(d:AppData)=>AppData)=>Promise<void>;replaceData:(d:AppData)=>Promise<void>;reset:()=>Promise<void>;clearError:()=>void};
const validateTransaction=(v:TransactionInput,data:AppData)=>{if(!isPositiveMoney(v.amount)||!isFinancialDate(v.date)||!v.description.trim()||!v.category.trim())throw new Error("Revisa los datos del movimiento.");if(!data.accounts.some(a=>a.id===v.accountId&&!a.archivedAt))throw new Error("Selecciona una cuenta válida.");if(v.type==="transfer"&&(!v.destinationAccountId||v.destinationAccountId===v.accountId||!data.accounts.some(a=>a.id===v.destinationAccountId&&!a.archivedAt)))throw new Error("Elige dos cuentas diferentes.")};
export const useAppStore=create<State>((set,get)=>{
 const commit=async(data:AppData)=>{set({busy:true,error:null});try{await repo.save(data);set({data,busy:false})}catch(e){set({busy:false,error:e instanceof Error?e.message:"No se pudo guardar el cambio."});throw e}};
 return{data:emptyData(),hydrated:false,workspace:"personal",drawerOpen:false,editingTransactionId:null,draftTransactionType:"expense",busy:false,error:null,
 hydrate:async()=>{const saved=await repo.load();const demo=process.env.NEXT_PUBLIC_DEMO_DATA==="true";set({data:saved??(demo?seedData:emptyData()),hydrated:true,error:repo.lastLoadError})},setWorkspace:workspace=>set({workspace}),setPeriod:async p=>{if(!/^\d{4}-\d{2}$/.test(p))return;await commit({...get().data,settings:{...get().data.settings,selectedPeriod:p}})},openDrawer:(id)=>{const value=String(id);const type=(["expense","income","transfer"] as string[]).includes(value)?value as TransactionType:"expense";set({drawerOpen:true,editingTransactionId:typeof id==="string"&&!(["expense","income","transfer"] as string[]).includes(id)?id:null,draftTransactionType:type,error:null})},closeDrawer:()=>set({drawerOpen:false,editingTransactionId:null,error:null}),
 addTransaction:async v=>{validateTransaction(v,get().data);const stamp=new Date().toISOString();const t:Transaction={...v,amount:roundMoney(v.amount),description:v.description.trim(),category:v.category.trim(),id:crypto.randomUUID(),createdAt:stamp,updatedAt:stamp,workspace:get().workspace};await commit({...get().data,transactions:[t,...get().data.transactions]});set({drawerOpen:false,editingTransactionId:null})},
 updateTransaction:async(id,v)=>{validateTransaction(v,get().data);const stamp=new Date().toISOString();await commit({...get().data,transactions:get().data.transactions.map(t=>t.id===id?{...t,...v,amount:roundMoney(v.amount),description:v.description.trim(),category:v.category.trim(),updatedAt:stamp}:t)});set({drawerOpen:false,editingTransactionId:null})},
 deleteTransaction:async id=>{await commit({...get().data,transactions:get().data.transactions.filter(t=>t.id!==id)})},
 createAccount:async v=>{if(!v.name.trim()||!Number.isFinite(v.initialBalance))throw new Error("Revisa los datos de la cuenta.");const stamp=new Date().toISOString();const a:Account={...v,name:v.name.trim(),initialBalance:roundMoney(v.initialBalance),id:crypto.randomUUID(),createdAt:stamp,updatedAt:stamp};await commit({...get().data,accounts:[...get().data.accounts,a]})},
 updateAccount:async(id,v)=>{if(v.name!==undefined&&!v.name.trim())throw new Error("El nombre es obligatorio.");await commit({...get().data,accounts:get().data.accounts.map(a=>a.id===id?{...a,...v,name:v.name?.trim()??a.name,initialBalance:v.initialBalance===undefined?a.initialBalance:roundMoney(v.initialBalance),updatedAt:new Date().toISOString()}:a)})},
 archiveAccount:async id=>{const referenced=get().data.transactions.some(t=>t.accountId===id||t.destinationAccountId===id);if(!referenced)await commit({...get().data,accounts:get().data.accounts.filter(a=>a.id!==id)});else await commit({...get().data,accounts:get().data.accounts.map(a=>a.id===id?{...a,archivedAt:new Date().toISOString(),updatedAt:new Date().toISOString()}:a)})},
 updateData:async fn=>commit(fn(get().data)),replaceData:async data=>commit(data),reset:async()=>{set({busy:true,error:null});try{await repo.clear();set({data:emptyData(),busy:false})}catch(e){set({busy:false,error:e instanceof Error?e.message:"No se pudieron eliminar los datos."});throw e}},clearError:()=>set({error:null})};
});
