import type { Account, AppData, InventoryItem, Product, Transaction } from "@/domain/models";
import { periodOf } from "./financial-date";
import { roundMoney, sumMoney } from "./money";
export const transactionsForPeriod=(items:Transaction[],period:string,workspace:"personal"|"business"="personal")=>items.filter(t=>periodOf(t.date)===period&&t.workspace===workspace);
export const sumByType=(items:Transaction[],type:"income"|"expense",workspace:"personal"|"business"="personal")=>sumMoney(items.filter(t=>t.type===type&&t.workspace===workspace).map(t=>t.amount));
export const monthly=(items:Transaction[],type:"income"|"expense",period:string,workspace:"personal"|"business"="personal")=>sumByType(transactionsForPeriod(items,period,workspace),type,workspace);
export function accountBalance(account:Account,items:Transaction[]){return roundMoney(items.reduce((balance,t)=>{if(t.type==="income"&&t.accountId===account.id)return balance+t.amount;if(t.type==="expense"&&t.accountId===account.id)return balance-t.amount;if(t.type==="transfer"&&t.accountId===account.id)return balance-t.amount;if(t.type==="transfer"&&t.destinationAccountId===account.id)return balance+t.amount;return balance},account.initialBalance))}
export const totalBalance=(data:AppData)=>sumMoney(data.accounts.map(a=>accountBalance(a,data.transactions)));
/** Accounts are financial assets; data.assets contains manual non-account assets only. */
export const totalAssets=(data:AppData)=>roundMoney(totalBalance(data)+sumMoney(data.assets.filter(a=>!(a.id==="as1"&&a.name==="Efectivo y cuentas")).map(a=>a.value)));
export const netWorth=(data:AppData)=>roundMoney(totalAssets(data)-sumMoney(data.liabilities.map(a=>a.value)));
export function availableToSpend(data:AppData,period:string){const monthTx=transactionsForPeriod(data.transactions,period);const remainingRecurring=sumMoney(data.recurring.filter(r=>r.active&&r.type==="expense"&&!monthTx.some(t=>t.type==="expense"&&t.recurring&&t.description===r.description)).map(r=>r.amount));const saved=sumMoney(data.goals.flatMap(g=>g.contributions).filter(c=>periodOf(c.date)===period).map(c=>c.amount));const remainingTarget=Math.max(0,roundMoney(data.settings.monthlySavingsTarget-saved));return roundMoney(monthly(data.transactions,"income",period)-monthly(data.transactions,"expense",period)-remainingRecurring-remainingTarget)}
export const budgetSpent=(data:AppData,category:string,period:string)=>roundMoney(transactionsForPeriod(data.transactions,period).filter(t=>t.type==="expense"&&t.category===category).reduce((s,t)=>s+t.amount,0));
export const goalAmount=(goal:AppData["goals"][number])=>sumMoney(goal.contributions.map(c=>c.amount));
export const productMetrics=(p:Product)=>{const unitCost=sumMoney(p.costs.map(c=>c.amount));const profit=roundMoney(p.salePrice-unitCost);return{unitCost,profit,margin:p.salePrice===0?0:roundMoney(profit/p.salePrice*100)}};
export const inventoryValue=(i:InventoryItem)=>roundMoney(i.quantity*i.unitCost);
export const inventoryStatus=(i:InventoryItem):"Disponible"|"Stock bajo"|"Agotado"=>i.quantity<=0?"Agotado":i.quantity<=i.minimumStock?"Stock bajo":"Disponible";
export const safeRatio=(a:number,b:number,scale=1)=>!Number.isFinite(a)||!Number.isFinite(b)||b===0?null:roundMoney(a/b*scale);
export function statement(data:AppData,period=data.settings.selectedPeriod){const tx=transactionsForPeriod(data.transactions,period,"business");const sales=sumByType(tx,"income","business");const cogs=sumMoney(data.products.map(p=>roundMoney(productMetrics(p).unitCost*p.sales)));const expenses=sumByType(tx,"expense","business");return{sales,cogs,gross:roundMoney(sales-cogs),expenses,net:roundMoney(sales-cogs-expenses)}}
export function balanceSheet(data:AppData){const assets=totalAssets(data),liabilities=sumMoney(data.liabilities.map(a=>a.value)),equity=roundMoney(assets-liabilities);return{assets,liabilities,equity,totalLiabilitiesAndEquity:roundMoney(liabilities+equity),balanced:roundMoney(liabilities+equity)===assets}}
export function actualCashFlow(data:AppData,period:string,workspace:"personal"|"business"="business"){const income=monthly(data.transactions,"income",period,workspace),expenses=monthly(data.transactions,"expense",period,workspace);return{income,expenses,net:roundMoney(income-expenses)}}
export function projectedCashFlow(data:AppData,period:string,workspace:"personal"|"business"="business"){const actual=actualCashFlow(data,period,workspace);const recurringIncome=sumMoney(data.recurring.filter(r=>r.active&&r.type==="income").map(r=>r.amount));const recurringExpenses=sumMoney(data.recurring.filter(r=>r.active&&r.type==="expense").map(r=>r.amount));return{income:roundMoney(actual.income+recurringIncome),expenses:roundMoney(actual.expenses+recurringExpenses),net:roundMoney(actual.net+recurringIncome-recurringExpenses),projected:true as const}}
