import type { AppData } from "@/domain/models";
const now = "2026-08-10T10:00:00.000Z";
const rec = <T extends object>(id: string, value: T) => ({ id, createdAt: now, updatedAt: now, ...value });
export const seedData: AppData = {
  profile: rec("demo-profile",{name:"Persona Demo"}),
  accounts: [rec("acc-bank",{name:"BCP Principal",type:"bank" as const,initialBalance:18400,currency:"PEN" as const}),rec("acc-wallet",{name:"Yape",type:"wallet" as const,initialBalance:1240,currency:"PEN" as const}),rec("acc-savings",{name:"Ahorros",type:"savings" as const,initialBalance:12200,currency:"PEN" as const})],
  transactions: [rec("t1",{type:"income" as const,amount:8500,category:"Ingresos",accountId:"acc-bank",date:"2026-08-02",description:"Honorarios agosto",workspace:"personal" as const}),rec("t2",{type:"expense" as const,amount:285,category:"Alimentación",accountId:"acc-wallet",date:"2026-08-08",description:"Supermercado Wong",workspace:"personal" as const}),rec("t3",{type:"expense" as const,amount:78.5,category:"Transporte",accountId:"acc-wallet",date:"2026-08-09",description:"Movilidad",workspace:"personal" as const}),rec("t4",{type:"income" as const,amount:12400,category:"Ventas",accountId:"acc-bank",date:"2026-08-04",description:"Ventas semanales",workspace:"business" as const}),rec("t5",{type:"expense" as const,amount:1450,category:"Servicios",accountId:"acc-bank",date:"2026-08-06",description:"Servicios del local",workspace:"business" as const})],
  budgets:[rec("b1",{category:"Alimentación",limit:1200}),rec("b2",{category:"Transporte",limit:600}),rec("b3",{category:"Vivienda",limit:2200}),rec("b4",{category:"Entretenimiento",limit:450})],
  goals:[rec("g1",{name:"Fondo de emergencia",targetAmount:18000,currentAmount:12600,targetDate:"2026-12-31",contributions:[{id:"c1",amount:12600,date:"2026-07-01"}]}),rec("g2",{name:"Viaje al sur",targetAmount:6000,currentAmount:2100,targetDate:"2027-03-01",contributions:[{id:"c2",amount:2100,date:"2026-07-01"}]})],
  assets:[rec("as1",{name:"Efectivo y cuentas",value:40390,kind:"Corriente"}),rec("as2",{name:"Departamento",value:180000,kind:"Propiedad"}),rec("as3",{name:"Equipos",value:18500,kind:"Negocio"})], liabilities:[rec("l1",{name:"Préstamo hipotecario",value:94000,kind:"Largo plazo"}),rec("l2",{name:"Tarjeta de crédito",value:3200,kind:"Corriente"})],
  products:[rec("p1",{name:"Café especial 250g",salePrice:38,sales:210,status:"active" as const,costs:[{id:"pc1",name:"Café y empaque",amount:13.2,type:"material" as const},{id:"pc2",name:"Tostado",amount:4.8,type:"labor" as const}]}),rec("p2",{name:"Pack degustación",salePrice:72,sales:86,status:"active" as const,costs:[{id:"pc3",name:"Insumos",amount:31,type:"material" as const},{id:"pc4",name:"Armado",amount:6,type:"labor" as const}]})],
  inventory:[rec("i1",{productId:"p1",quantity:84,unitCost:18,minimumStock:30,adjustments:[]}),rec("i2",{productId:"p2",quantity:12,unitCost:37,minimumStock:15,adjustments:[]})], recurring:[rec("r1",{type:"expense" as const,amount:680,day:20,description:"Servicios y suscripciones",active:true})],
  snapshots:[rec("s1",{month:"Mar",assets:216000,liabilities:104000}),rec("s2",{month:"Abr",assets:221000,liabilities:102000}),rec("s3",{month:"May",assets:226000,liabilities:100500}),rec("s4",{month:"Jun",assets:232000,liabilities:99000}),rec("s5",{month:"Jul",assets:237000,liabilities:98500}),rec("s6",{month:"Ago",assets:238890,liabilities:97200})], business:rec("biz1",{name:"Mi negocio"}), settings:{currency:"PEN",appearance:"dark",monthlySavingsTarget:1200,schemaVersion:2,selectedPeriod:"2026-08",guideCompleted:true,categories:{personal:["Alimentación","Transporte","Vivienda","Servicios","Entretenimiento","Compras","Ingresos","Otros"],business:["Ventas","Costos","Gastos operativos","Servicios","Otros"]}}
};
