import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, BarChart3, BriefcaseBusiness, Check, Download, Menu, ShieldCheck, Smartphone, WalletCards, WifiOff } from "lucide-react";

export const metadata:Metadata={title:"Nexo — Finanzas personales y de negocio",description:"Gestiona tus finanzas personales y de negocio desde una aplicación local-first, instalable y disponible sin conexión."};

const personal=["Ingresos y gastos","Cuentas","Presupuestos","Metas","Patrimonio","Flujo de dinero"];
const business=["Productos y costeo","Margen por unidad","Inventario","Flujo de caja","Estado de resultados","Balance general","Indicadores financieros"];
const faqs=[
  ["¿Necesito crear una cuenta?","No. Nexo Local V1.1 no requiere registro ni inicio de sesión."],
  ["¿Dónde se guardan mis datos?","En el almacenamiento local de este navegador y dispositivo."],
  ["¿Nexo tiene nube?","No. Local V1.1 no usa una base de datos en la nube ni sincronización automática."],
  ["¿Funciona sin Internet?","Después de una primera carga y cacheo correctos, la funcionalidad local está disponible sin conexión donde el navegador lo permite."],
  ["¿Puedo pasar mis datos a otro dispositivo?","Sí, mediante Exportar respaldo e Importar respaldo desde Configuración."],
  ["¿Puedo probarlo sin usar mis datos?","Sí. El modo demo utiliza un espacio separado y no modifica tus datos normales."],
] as const;

export default function LandingPage(){return <main className="landing">
  <header className="landing-nav"><Link href="/" className="landing-brand"><span className="brand-mark">n</span><strong>nexo</strong></Link><nav aria-label="Navegación principal"><a href="#caracteristicas">Características</a><a href="#como-funciona">Cómo funciona</a><a href="#privacidad">Privacidad</a><a href="#faq">FAQ</a></nav><div className="landing-actions"><Link className="secondary-button" href="/dashboard?demo=1">Probar demo</Link><Link className="primary-button" href="/dashboard?mode=real">Empezar <ArrowRight size={16}/></Link></div><details className="landing-menu"><summary aria-label="Abrir menú"><Menu/></summary><div><a href="#caracteristicas">Características</a><a href="#como-funciona">Cómo funciona</a><a href="#privacidad">Privacidad</a><a href="#faq">FAQ</a><Link href="/dashboard?demo=1">Probar demo</Link><Link href="/dashboard?mode=real">Empezar</Link></div></details></header>
  <section className="landing-hero"><div><span className="landing-kicker">FINANZAS CLARAS · DATOS LOCALES</span><h1>Controla tus finanzas<br/><em>sin complicarlas.</em></h1><p>Gestiona ingresos, gastos, presupuestos, patrimonio y las finanzas de tu negocio desde una sola aplicación.</p><div className="hero-actions"><Link className="primary-button" href="/dashboard?mode=real">Empezar <ArrowRight size={17}/></Link><Link className="secondary-button" href="/dashboard?demo=1">Probar demo</Link></div><ul className="trust-list"><li><ShieldCheck/>Tus datos permanecen en tu dispositivo</li><li><WifiOff/>Funciona sin conexión</li><li><Check/>Sin registro</li></ul></div><ProductPreview/></section>
  <section id="caracteristicas" className="landing-section"><div className="section-heading"><span>TODO EN UN SOLO LUGAR</span><h2>Tu dinero personal y tu negocio,<br/>con una vista más clara.</h2></div><div className="feature-split"><article><WalletCards/><h3>Finanzas personales</h3><p>Entiende tu día a día, organiza tus planes y conoce tu posición financiera.</p><ul>{personal.map(item=><li key={item}><Check/>{item}</li>)}</ul></article><article><BriefcaseBusiness/><h3>Finanzas de negocio</h3><p>Una base práctica para conocer productos, costos y resultados de un pequeño negocio.</p><ul>{business.map(item=><li key={item}><Check/>{item}</li>)}</ul></article></div></section>
  <section id="como-funciona" className="landing-section how"><div className="section-heading"><span>CÓMO FUNCIONA</span><h2>Empieza en tres pasos.</h2></div><div className="steps"><article><b>01</b><h3>Empieza</h3><p>Indica tu nombre y crea tu primera cuenta.</p></article><article><b>02</b><h3>Registra</h3><p>Añade ingresos, gastos y transferencias.</p></article><article><b>03</b><h3>Entiende</h3><p>Nexo calcula automáticamente balances, presupuestos y patrimonio.</p></article></div></section>
  <section id="privacidad" className="landing-section local-first"><div><span>LOCAL-FIRST</span><h2>Tus datos son tuyos.</h2><p>Nexo Local V1.1 guarda tu información financiera en el almacenamiento local de tu navegador. No hay login, base de datos en la nube ni sincronización automática.</p><p>Puedes exportar e importar un respaldo cuando quieras mover o proteger tus datos.</p><Link href="/help#backups">Cómo funcionan los respaldos <ArrowRight size={16}/></Link></div><div className="privacy-points"><article><ShieldCheck/><h3>En tu dispositivo</h3><p>Los movimientos y preferencias permanecen en el navegador que utilizas.</p></article><article><Download/><h3>Respaldo portable</h3><p>Exporta un archivo JSON y restáuralo en otro navegador.</p></article></div></section>
  <section className="landing-section pwa-section"><div><Smartphone/><span>APLICACIÓN INSTALABLE</span><h2>Instala Nexo como una aplicación.</h2><p>Disponible para instalación en Desktop, Android y iPhone cuando el navegador y la plataforma lo permiten. El uso offline requiere una primera carga y cacheo correctos.</p></div></section>
  <section id="faq" className="landing-section faq"><div className="section-heading"><span>PREGUNTAS FRECUENTES</span><h2>Respuestas claras.</h2></div>{faqs.map(([question,answer])=><details key={question}><summary>{question}</summary><p>{answer}</p></details>)}</section>
  <section className="landing-final"><h2>Empieza a entender mejor tus finanzas.</h2><div><Link className="primary-button" href="/dashboard?mode=real">Empezar</Link><Link className="secondary-button" href="/dashboard?demo=1">Probar demo</Link></div></section>
  <footer><span>Nexo Local V1.1</span><nav><Link href="/help">Ayuda</Link><a href="#privacidad">Privacidad y datos locales</a></nav></footer>
</main>}

function ProductPreview(){return <div className="product-preview" aria-label="Vista previa del Dashboard de Nexo"><div className="preview-top"><span><i/>nexo</span><small>Resumen</small></div><div className="preview-body"><aside><i className="active"/><i/><i/><i/><i/></aside><div><span className="preview-label">DISPONIBLE PARA GASTAR</span><strong>S/ 1,842.50</strong><small>Tu panorama financiero en un vistazo</small><div className="preview-metrics"><span><small>Saldo total</small><b>S/ 7,240</b></span><span><small>Patrimonio</small><b className="positive">S/ 38,420</b></span></div><div className="preview-chart"><BarChart3/><svg viewBox="0 0 500 110" role="img" aria-label="Gráfico ascendente de ejemplo"><path d="M5 92 C65 55 100 92 150 55 S235 78 280 38 S365 65 410 29 S465 42 495 8"/></svg></div></div></div></div>}
