"use client";
import type { ReactNode } from "react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
export const money=(n:number)=>new Intl.NumberFormat("es-PE",{style:"currency",currency:"PEN",minimumFractionDigits:2}).format(n).replace("PEN","S/");
export function PageHeader({title,description,action}:{title:string;description:string;action?:ReactNode}){return <div className="page-header"><div><h1>{title}</h1><p>{description}</p></div>{action}</div>}
export function Card({children,className="",id}:{children:ReactNode;className?:string;id?:string}){return <section id={id} className={`card ${className}`}>{children}</section>}
export function Metric({label,value,detail,tone=""}:{label:string;value:string;detail?:string;tone?:string}){return <Card className="metric"><span>{label}</span><strong className={tone}>{value}</strong>{detail&&<small>{detail}</small>}</Card>}
export function ProgressRow({label,value,total}:{label:string;value:number;total:number}){const rawPct=total>0?value/total*100:0;const visualPct=Math.max(0,Math.min(100,rawPct));const tone=rawPct>=100?"danger":rawPct>=80?"warning":"";return <div className="progress-row"><div><strong>{label}</strong><span>{money(value)} de {money(total)} / {Math.round(rawPct)}%</span></div><div className={`progress-track ${tone}`}><i style={{width:`${visualPct}%`}}/></div></div>}
export function MoneyChart({data}:{data:{name:string;value:number}[]}){return <div className="chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data}><defs><linearGradient id="mint" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#65d8ab" stopOpacity={.28}/><stop offset="1" stopColor="#65d8ab" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="#242a28"/><XAxis dataKey="name" axisLine={false} tickLine={false} tick={{fill:"#7f8985",fontSize:12}}/><YAxis hide/><Tooltip contentStyle={{background:"#171c1a",border:"1px solid #29312e",borderRadius:12}} formatter={(v)=>money(Number(v))}/><Area type="monotone" dataKey="value" stroke="#65d8ab" strokeWidth={2.2} fill="url(#mint)"/></AreaChart></ResponsiveContainer></div>}
